// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lvrusgtopkuuuxgdzacf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cnVzZ3RvcGt1dXV4Z2R6YWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTgwNTUsImV4cCI6MjA2OTg3NDA1NX0.nA1LNbKkz_rsMqNoyA4QpHs-G5d4GnphcMIp32Hh07g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);